{/*import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const engravers = localFont({ src: "./assets/font/EngraversGothic.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${engravers.className} antialiased scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}*/}
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Rubik } from "next/font/google";

// Rubik глобально (по умолчанию для всего сайта)
const rubik = Rubik({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700", "800", "900"],
  display: "swap",
  variable: "--font-rubik",
});

// Engravers — только для тех блоков, где нужен
const engravers = localFont({
  src: "./assets/font/EngraversGothic.ttf",
  variable: "--font-engravers",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${rubik.variable} ${engravers.variable}`}>
      {/* По умолчанию Rubik */}
      <body className={`${rubik.className} antialiased scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}

