import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const engravers = localFont({ src: "./assets/font/EngraversGothic.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${engravers.className} antialiased scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}
